---
version: '3.8'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2
    networks:
      - app-network
  service1:
    build: ./service_1
    expose:
      - "8001"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8001/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  service2:
    build: ./service_2
    expose:
      - "5000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
networks:
  app-network:
    driver: bridge
...
